%% write_obj 
% Write mesh data to OBJ file

%% Syntax
%    write_obj(filename,face,vertex,color)

%% Description
%   'vertex' is a 'vert_number x 3' array specifying the position of the vertices.
%   'face' is a 'face_number x 3' array specifying the connectivity of the mesh.
%
% 'color' is a 'vert_number x 3 or face_number x 3' array specifying the color of the vertices or faces.

%%   Example
%   write_obj('cube.obj',face,vertex);

%   Copyright 2014 Computational Geometry Group,  Mathematics Dept., CUHK
%   http://www.lokminglui.com/

function write_obj(filename,face,vertex)

fid = fopen(filename,'wt');
if( fid==-1 )
    error('Can''t open the file.');
    return;
end

nvert = size(vertex, 1);
nface = size(face, 1);
nvert_face = size(face, 2);

%write logo
fprintf (fid, '#Generated by geometric processing package.\n');

%write vertex
%fprintf (fid, '# Vertex Definitions\n');
for i = 1:nvert
    fprintf (fid, 'v %.6f %.6f %.6f %.1f\n',vertex(i,1), vertex(i,2), vertex(i,3), 1);
end

%write face
%fprintf (fid, '# Face Definitions\n');
for i = 1:nface
    fprintf (fid, '%s ','f');
    for j = 1:nvert_face
        fprintf (fid, '%d ',face(i,j)-1);
    end
    fprintf (fid, '\n');
end

fclose(fid);

