%% write_off 
% Write mesh data to OFF file

%% Syntax
%  write_off(filename,face,vertex,color)

%% Description
%   filename specify the file to write.
%  'vertex' is a 'vert_number x 3' array specifying the position of the vertices.
%  'face' is a 'face_number x 3' array specifying the connectivity of the mesh.
%  'color' is a 'vert_number x 3 or face_number x 3' array specifying the color of the vertices or faces.

%%  Example
%  [face,vertex,color] = write_off('2_2.off');

%% Contribution
%  Author: Meng Bin
%  History:  2014/03/05 file created
%  Revised: 2014/03/07 by Meng Bin, Block write to enhance writing speed.
% 
%  Copyright 2014 Computational Geometry Group
%  Department of Mathematics, CUHK
%  http://www.lokminglui.com

function write_off(filename,face,vertex,color)

if nargin < 4
    color = [];
end

fid = fopen(filename,'wt');
if( fid==-1 )
    error('Can''t open the file.');
    return;
end

nvert = size(vertex, 1);
nface = size(face, 1);
nvert_face = size(face, 2);

ncolor =0;
if ~isempty(color)
    ncolor = size(color, 1);
end


fprintf (fid, 'OFF\n');
fprintf (fid, '#Generated by geometric processing package.\n');
fprintf (fid, '%d %d %d\n',nvert, nface, 0);

if nvert == ncolor 
	vertex = [vertex';color']';
end
if nface == ncolor && nvert ~= ncolor
	face =[zeros(1,nface)+nvert_face; face'-1;color']';
else
	face =[zeros(1,nface)+nvert_face;face'-1]';
end
dlmwrite(filename,vertex,'-append',...  
         'delimiter',' ',...
         'precision', 6,...
         'newline','pc');
		 
dlmwrite(filename,face,'-append',...  
         'delimiter',' ',...
         'newline','pc');
		 
fclose(fid);

end

